{
 "title": "OTUS HomeWork Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "App - Error Rate (5XX errors)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{status =~ \"5.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Ingress - Error rate (5XX)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status =~ \"5.+\", path =~ \"/otusapp/fedyiv.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "App - RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Ingress - RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum ( rate(nginx_ingress_controller_request_duration_seconds_count{path =~ \"/otusapp/fedyiv.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Ingress - Latency -  max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, (sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))) * 1000"
    }
   ]
  },
  {
   "title": "App - Latency -  max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, (sum by (le, uri) (rate(http_server_requests_seconds_bucket[1m])))) * 1000"
    }
   ]
  },
  {
   "title": "Ingress - Latenvy 0.99 quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))) * 1000"
    }
   ]
  },
  {
   "title": "App - Latenvy 0.99 quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (sum by (le, uri) (rate(http_server_requests_seconds_bucket[1m])))) * 1000"
    }
   ]
  },
  {
   "title": "App - Latenvy 0.95 quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, (sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))) * 1000"
    }
   ]
  },
  {
   "title": "App - Latenvy 0.95 quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, (sum by (le, uri) (rate(http_server_requests_seconds_bucket[1m])))) * 1000\n"
    }
   ]
  },
  {
   "title": "Ingress- Latency 0.5 quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))) * 1000"
    }
   ]
  },
  {
   "title": "App - Latency  0.5 quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le, uri) (rate(http_server_requests_seconds_bucket[1m])))) * 1000\n"
    }
   ]
  },
  {
   "title": "Application Pods Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name!~\"POD\", pod =~ \"myapp-fedyiv-otus-hw5-chart-78c54d7b74-m6qwm|myapp-fedyiv-otus-hw5-chart-78c54d7b74-rw8zn\"}) by (pod)\n"
    }
   ]
  },
  {
   "title": "CPU usage by app pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod =~ \"myapp-fedyiv-otus-hw5-chart-78c54d7b74-m6qwm|myapp-fedyiv-otus-hw5-chart-78c54d7b74-rw8zn\"}[1m])) by (pod)"
    }
   ]
  }
 ]
}