apiVersion: v1
kind: ConfigMap
metadata:
  name: hw2-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://my-release-postgresql.default.svc.cluster.local:5432/postgres
  SPRING_DATABASE_URL: postgres
#  SPRING_DATASOURCE_PASSWORD: P8q9s72eJO